from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Protocol

from sqlalchemy import select
from sqlalchemy.orm import Session

from manotron.config import load_settings
from manotron.db import init_db, session_scope
from manotron.files import file_candidate, iter_supported_files
from manotron.models import (
    Invoice,
    InvoiceLine,
    LineLocationDeduction,
    ScanRun,
    SourceFile,
)
from manotron.openai_client import OpenAIInvoiceExtractor
from manotron.schemas import ExtractedInvoice, ManotronSettings


class InvoiceExtractor(Protocol):
    def extract(self, path: Path) -> ExtractedInvoice: ...


@dataclass
class ScanSummary:
    files_seen: int = 0
    files_processed: int = 0
    files_failed: int = 0
    files_skipped: int = 0


class MockInvoiceExtractor:
    def extract(self, path: Path) -> ExtractedInvoice:
        stem = path.stem.upper().replace(" ", "-")
        return ExtractedInvoice.model_validate(
            {
                "invoice_reference_id": f"MOCK-{stem}",
                "invoice_date": date.today().isoformat(),
                "lines": [
                    {
                        "product_reference_id": "MOCK-PRODUCT",
                        "quantity_deducted": 1,
                        "location_deductions": [
                            {
                                "location": "MOCK-LOCATION",
                                "quantity": 1,
                                "source": "inferred",
                                "confidence": 1.0,
                            }
                        ],
                        "confidence": 1.0,
                        "notes": "Generated by --mock-extract.",
                    }
                ],
                "confidence": 1.0,
                "notes": "Generated by --mock-extract.",
            }
        )


def scan_configured_folder(mock_extract: bool = False) -> ScanSummary:
    settings = load_settings()
    if not settings.watch_folder:
        raise RuntimeError("No watch folder configured. Run `manotron init --folder /path`.")
    extractor: InvoiceExtractor = MockInvoiceExtractor() if mock_extract else OpenAIInvoiceExtractor(settings)
    return scan_folder(Path(settings.watch_folder), settings, extractor)


def scan_folder(folder: Path, settings: ManotronSettings, extractor: InvoiceExtractor) -> ScanSummary:
    folder = folder.expanduser().resolve()
    init_db(settings.db_path)
    summary = ScanSummary()
    started_at = datetime.now(timezone.utc)

    with session_scope(settings.db_path) as session:
        scan_run = ScanRun(started_at=started_at, folder=str(folder), status="running")
        session.add(scan_run)
        session.flush()

        for path in iter_supported_files(folder):
            summary.files_seen += 1
            _scan_one_file(path, session, settings, extractor, summary)

        scan_run.files_seen = summary.files_seen
        scan_run.files_processed = summary.files_processed
        scan_run.files_failed = summary.files_failed
        scan_run.files_skipped = summary.files_skipped
        scan_run.finished_at = datetime.now(timezone.utc)
        scan_run.status = "completed" if summary.files_failed == 0 else "completed_with_errors"

    return summary


def _scan_one_file(
    path: Path,
    session: Session,
    settings: ManotronSettings,
    extractor: InvoiceExtractor,
    summary: ScanSummary,
) -> None:
    candidate = file_candidate(path)
    existing = session.scalar(
        select(SourceFile).where(SourceFile.sha256_hash == candidate.sha256_hash)
    )
    if existing:
        existing.last_scanned_at = datetime.now(timezone.utc)
        summary.files_skipped += 1
        return

    now = datetime.now(timezone.utc)
    source_file = SourceFile(
        path=str(candidate.path),
        filename=candidate.path.name,
        sha256_hash=candidate.sha256_hash,
        size_bytes=candidate.size_bytes,
        created_at_fs=_parse_datetime(candidate.created_at_fs),
        modified_at_fs=_parse_datetime(candidate.modified_at_fs),
        first_seen_at=now,
        last_scanned_at=now,
        status="pending",
    )
    session.add(source_file)
    session.flush()

    try:
        extracted = extractor.extract(candidate.path)
        _store_invoice(session, source_file, extracted, settings.openai_model)
    except Exception as exc:
        source_file.status = "failed"
        source_file.error_message = str(exc)
        summary.files_failed += 1
        return

    source_file.status = "processed"
    summary.files_processed += 1


def _store_invoice(
    session: Session,
    source_file: SourceFile,
    extracted: ExtractedInvoice,
    model_name: str,
) -> Invoice:
    invoice = Invoice(
        source_file_id=source_file.id,
        invoice_reference_id=extracted.invoice_reference_id,
        invoice_date=_parse_date(extracted.invoice_date),
        extracted_at=datetime.now(timezone.utc),
        model_name=model_name,
        raw_text=None,
        raw_llm_json=extracted.model_dump_json(),
        confidence=extracted.confidence,
        notes=extracted.notes,
    )
    session.add(invoice)
    session.flush()

    for extracted_line in extracted.lines:
        product_locations = ";".join(
            deduction.location for deduction in extracted_line.location_deductions
        )
        locations_quantity = ";".join(
            f"{deduction.location}::{deduction.quantity}"
            for deduction in extracted_line.location_deductions
        )
        line = InvoiceLine(
            invoice_id=invoice.id,
            product_reference_id=extracted_line.product_reference_id,
            product_locations=product_locations,
            quantity_deducted=extracted_line.quantity_deducted,
            locations_quantity=locations_quantity,
            confidence=extracted_line.confidence,
            notes=extracted_line.notes,
        )
        session.add(line)
        session.flush()

        for extracted_deduction in extracted_line.location_deductions:
            session.add(
                LineLocationDeduction(
                    invoice_line_id=line.id,
                    location=extracted_deduction.location,
                    quantity=extracted_deduction.quantity,
                    source=extracted_deduction.source,
                    confidence=extracted_deduction.confidence,
                )
            )

    return invoice


def _parse_date(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(value[:10])
    except ValueError:
        return None


def _parse_datetime(value: str) -> datetime:
    return datetime.fromisoformat(value)

